---

- name: Check if Servers OU exists
  win_shell: Get-ADOrganizationalUnit -Identity 'OU=Servers,DC=windomain,DC=local'
  register: servers_ou
- debug: var=servers_ou

- name: Creating Servers OU
  win_shell: New-ADOrganizationalUnit -Name "Servers" -Server "dc.windomain.local"
  when: servers_ou is failed

- name: Check if Workstations OU exists
  win_shell: Get-ADOrganizationalUnit -Identity 'OU=Workstations,DC=windomain,DC=local'
  register: servers_ou
- debug: var=ws_ou

- name: Creating Workstations OU
  win_shell: New-ADOrganizationalUnit -Name "Workstations" -Server "dc.windomain.local"
  when: ws_ou is failed
