---

- name: Set fact for WEF GPO
  set_fact:
    GPOName: 'Windows Event Forwarding Server'
    GPOImportPath: "{{ detectionlab_gitroot }}\\vagrant\\resources\\GPO\\wef_configuration"
    OU_list:
      - "OU=Servers,dc=windomain,dc=local"
      - "OU=Domain Controllers,dc=windomain,dc=local"
      - "OU=Workstations,dc=windomain,dc=local"

- include: gpo.yml

- name: Set fact for WEF custom event channel permissions GPO
  set_fact:
    GPOName: 'Custom Event Channel Permissions'
    GPOImportPath: "{{ detectionlab_gitroot }}\\vagrant\\resources\\GPO\\wef_configuration"

- include: gpo.yml
