---

- name: Set fact for RDP User GPO
  set_fact:
    GPOName: 'Allow Domain Users RDP'
    GPOImportPath: "{{ detectionlab_gitroot }}\\vagrant\\resources\\GPO\\rdp_users"
    OU_list:
      - "OU=Servers,dc=windomain,dc=local"
      - "OU=Workstations,dc=windomain,dc=local"

- include: gpo.yml
