---

- name: Ensure appropriate services are started
  win_service:
    name: "{{ item }}"
    state: started
    start_mode: auto
  with_items:
    - wuauserv

- name: Install security updates
  win_updates:
    category_names: SecurityUpdates
  when: dc_system_updates|bool

- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Check if existing DetectionLab directory
  win_stat:
    path: 'c:\DetectionLab'
  register: dir

- name: Git clone Detectionlab
  win_shell: git clone https://github.com/clong/DetectionLab.git
  args:
    chdir: 'c:\'
  when: not dir.stat.exists

- name: Install other applications with chocolatey
  win_chocolatey:
    name:
# utilities
      - NotepadPlusPlus
      - GoogleChrome
      - WinRar
# sysinternals
      - sysinternals
# extras
      - wireshark
      - winpcap
    state: present
  ignore_errors: "{{ _dc_chocolatey_ignore_errors | default(false) }}"

- name: Install classic-shell with chocolatey
  win_chocolatey:
    name:
# utilities
      - classic-shell
    state: present
    install_args: "ADDLOCAL=ClassicStartMenu"

- name: DetectionLab Menu
  win_command: '"C:\Program Files\Classic Shell\ClassicStartMenu.exe" -xml c:\DetectionLab\vagrant\resources\windows\MenuSettings.xml'
  when: dc_menu|bool

- name: Ensure directories exist
  win_file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - C:\Program Files\sysinternals
    - C:\Users\vagrant\AppData\Local\Temp
    - C:\Tools\Mimikatz
    - C:\Tmp

- name: Ensure etc\hosts is valid
  win_lineinfile:
    path: c:\windows\system32\drivers\etc\hosts
    regexp: "{{ item.re }}"
    line: "{{ item.l }}"
  with_items:
    - { re: '^\s*192.168.38.105    kolide', l: "        192.168.38.105    kolide\n" }
    - { re: '^\s*192.168.38.102    dc.windomain.local', l: "        192.168.38.102    dc.windomain.local\n" }

- include: provision.yml
- include: create-domain.yml

- include: palantir.yml

- name: Ensure Win Defender is not present
  win_feature:
    name: Windows-Defender-Features
    state: absent
  when: dc_defender_removed|bool

- include: redteam.yml

# FIXME! OU/GPO configuration requiring DC live, meaning reboot after promote
- name: Configure dc host
  win_shell: "{{ item }}"
  args:
    chdir: 'c:\DetectionLab\Vagrant\scripts'
  with_items:
    - ".\\configure-ou.ps1"
    - ".\\configure-wef-gpo.ps1"
    - ".\\configure-disable-windows-defender-gpo.ps1"
    - 'wevtutil el | Select-String -notmatch "Microsoft-Windows-LiveId" | Foreach-Object {wevtutil cl "$_"}'
    - "Set-SmbServerConfiguration -AuditSmb1Access $true -Force"
